# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01eeb81028f202d7d05a71a6cdadc18426c04ee88ab0f35df47a7b34fa2bdef722a1d54112ed5ea144547332a688c4731c5956482375b833de4f0a53c28c03ba

test:
  secret_key_base: c5044205ad4fba0dbb7fec694a6d8c7c25848727d2584b8dc04ef3f0cc568530f0c922576b341f71d2001a946a881b297e84dad066c6f442bbf8a74d2f83ba37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
